author: Diego Kiedanski

description: Diego Kiedanski's personal website.

hero_title: Hi, Diego here. I'm a computer scientist obsessed with climate change.
hero_description: "My work involves applied machine learning: from research to teaching and consulting. In September 2022, I will join Carbon13 as a prospective founder of a CleanTech startup."

linkedin: diego-kiedanski
github: kiedanski
email: ping@kiedanski.com

paginate: 9
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate
