name: Deploy Notion Blog to Github Pages

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/60 * * * *'
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-node@v2
        with:
          node-version: '17.6.0'
        

      - name: "Install npm and download from notion"  
        env: # Or as an environment variable
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          RELATIVE_PATH: "../"
        run: |
          python -m pip install pillow
          cp infrastructure/notion/package.json notion/
          cp infrastructure/notion/package-lock.json notion/
          cd notion 
          npm install
          node main.js
          cd ..     
          python notion/replace_links.py
          echo "kiedanski.com" > CNAME
     
      - name: Build
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'



